import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 为每个板块单独侧边栏（避免点击某一项时看到全部）
  kechengSidebar: [{type: 'autogenerated', dirName: 'kecheng'}],
  jingyanSidebar: [{type: 'autogenerated', dirName: 'jingyan'}],
  qudaoSidebar: [{type: 'autogenerated', dirName: 'qudao'}],
  gongjuSidebar: [{type: 'autogenerated', dirName: 'gongju'}],
  shipinSidebar: [{type: 'autogenerated', dirName: 'shipin'}],
  bokeSidebar: [{type: 'autogenerated', dirName: 'boke'}],
  // 书籍独立侧边栏
  shujiSidebar: [{type: 'autogenerated', dirName: 'shuji'}],
};

export default sidebars;
